<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Yadav" failures="3" tests="5" name="Test" time="32.66" errors="0" timestamp="2024-10-23T09:25:56 IST">
  <testcase classname="testCases.TC002_LoginTestDDT" name="verifyLoginTest" time="3.063"/>
  <testcase classname="testCases.TC002_LoginTestDDT" name="verifyLoginTest" time="1.853">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC002_LoginTestDDT.verifyLoginTest(TC002_LoginTestDDT.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginTest -->
  <testcase classname="testCases.TC002_LoginTestDDT" name="verifyLoginTest" time="2.329">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC002_LoginTestDDT.verifyLoginTest(TC002_LoginTestDDT.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginTest -->
  <testcase classname="testCases.TC002_LoginTestDDT" name="verifyLoginTest" time="11.693">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC002_LoginTestDDT.verifyLoginTest(TC002_LoginTestDDT.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginTest -->
  <testcase classname="testCases.TC002_LoginTestDDT" name="verifyLoginTest" time="5.346"/>
</testsuite> <!-- Test -->
